In [3]:
#Importing all the required libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [4]:
#Reading the data set 
df=pd.read_csv("C:/Users/HP/Documents/Python Scripts/Mevi Assignment/Projects/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
print(df.isnull().sum())
print(df.info())
print(df.describe())
print(df.shape)
df.value_counts()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000

Id   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species        
1    5.1            3.5           1.4            0.2           Iris-setosa        1
95   5.6            2.7           4.2            1.3           Iris-versicolor    1
97   5.7            2.9           4.2            1.3           Iris-versicolor    1
98   6.2            2.9           4.3            1.3           Iris-versicolor    1
99   5.1            2.5           3.0            1.1           Iris-versicolor    1
                                                                                 ..
51   7.0            3.2           4.7            1.4           Iris-versicolor    1
52   6.4            3.2           4.5            1.5           Iris-versicolor    1
53   6.9            3.1           4.9            1.5           Iris-versicolor    1
54   5.5            2.3           4.0            1.3           Iris-versicolor    1
150  5.9            3.0           5.1            1.8           Iris-virginica    

In [6]:
#Splitting the data in X and Y

x=df.drop(["Species"],axis=1)
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [7]:
y=df['Species']
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [8]:
print(x.shape)
print(y.shape)

(150, 5)
(150,)


In [9]:
#splitting the data into xtrain ytrain ytest xtest
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
print(x_train.shape)
print(y_train.shape)

(120, 5)
(120,)


In [11]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(random_state=0)

In [12]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [18]:
pred=clf.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(pred,y_test)
a=accuracy_score(pred,y_test)

In [20]:
print(cm)
a

[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]


0.9666666666666667

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf1=RandomForestClassifier(n_estimators=9)

In [22]:
clf1.fit(x_train,y_train)

RandomForestClassifier(n_estimators=9)

In [23]:
pred1=clf1.predict(x_test)

In [24]:
cm1=confusion_matrix(pred1,y_test)
a1=accuracy_score(pred1,y_test)

In [25]:
print(cm1)
print(a1)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0


In [26]:
l=[1,5.1,3.5,1.4,0.2]
l=np.array(l).reshape(1,-1)
l

array([[1. , 5.1, 3.5, 1.4, 0.2]])

In [27]:
a=clf1.predict(l)
if(a==0):
    print("The person do not have Heart diseases")
else:
    print("The person is suffuring from Heart diseases")

The person is suffuring from Heart diseases


c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [28]:
from sklearn.linear_model import LogisticRegression
clf2=lr=LogisticRegression(random_state=0)

In [29]:
clf2.fit(x_train,y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [31]:
pred2=clf2.predict(x_test)

In [32]:
cm2=confusion_matrix(pred2,y_test)
a2=accuracy_score(pred2,y_test)

In [33]:
print(cm2)
print(a2)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0
